"""initial schema fato_eventos_jornada and etl_log

Revision ID: 001
Revises: 
Create Date: 2026-06-12 10:55:22.843504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('view_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=False),
    sa.Column('finished_at', sa.String(length=32), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etl_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etl_log_view_name'), ['view_name'], unique=False)

    op.create_table('fato_eventos_jornada',
    sa.Column('evento_id', sa.String(length=64), nullable=False),
    sa.Column('paciente_id', sa.String(length=32), nullable=False),
    sa.Column('tipo_entidade', sa.String(length=16), nullable=False),
    sa.Column('entidade_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_principal', sa.String(length=32), nullable=False),
    sa.Column('timestamp_solicitacao', sa.String(length=32), nullable=True),
    sa.Column('timestamp_agendamento', sa.String(length=32), nullable=True),
    sa.Column('timestamp_realizacao', sa.String(length=32), nullable=True),
    sa.Column('timestamp_liberacao', sa.String(length=32), nullable=True),
    sa.Column('timestamp_alta_medica', sa.String(length=32), nullable=True),
    sa.Column('timestamp_alta_administrativa', sa.String(length=32), nullable=True),
    sa.Column('unidade', sa.String(length=128), nullable=True),
    sa.Column('especialidade', sa.String(length=128), nullable=True),
    sa.Column('tipo_evento', sa.String(length=128), nullable=True),
    sa.Column('situacao', sa.String(length=64), nullable=True),
    sa.Column('dt_carga', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('evento_id')
    )
    with op.batch_alter_table('fato_eventos_jornada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fato_eventos_jornada_especialidade'), ['especialidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_eventos_jornada_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_eventos_jornada_timestamp_principal'), ['timestamp_principal'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_eventos_jornada_tipo_entidade'), ['tipo_entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_eventos_jornada_unidade'), ['unidade'], unique=False)
        batch_op.create_index('ix_fato_filtros', ['tipo_entidade', 'unidade', 'especialidade', 'timestamp_principal'], unique=False)

    # ix_fato_active uses sqlite_where (partial index) which does NOT propagate
    # through batch_alter_table — must be created at top-level.
    op.create_index(
        'ix_fato_active',
        'fato_eventos_jornada',
        ['tipo_entidade', 'timestamp_principal'],
        sqlite_where=sa.text('deleted_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop top-level partial index first (created outside batch in upgrade).
    op.drop_index('ix_fato_active', table_name='fato_eventos_jornada')
    with op.batch_alter_table('fato_eventos_jornada', schema=None) as batch_op:
        batch_op.drop_index('ix_fato_filtros')
        batch_op.drop_index(batch_op.f('ix_fato_eventos_jornada_unidade'))
        batch_op.drop_index(batch_op.f('ix_fato_eventos_jornada_tipo_entidade'))
        batch_op.drop_index(batch_op.f('ix_fato_eventos_jornada_timestamp_principal'))
        batch_op.drop_index(batch_op.f('ix_fato_eventos_jornada_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_fato_eventos_jornada_especialidade'))

    op.drop_table('fato_eventos_jornada')
    with op.batch_alter_table('etl_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etl_log_view_name'))

    op.drop_table('etl_log')
    # ### end Alembic commands ###
